
---
  - name: Install default Apache web server
    hosts: all
    become: yes

    tasks:
     - name: Update apt
       apt: update_cache=yes

     - name: Install Apache
       apt: name=apache2 state=latest

     - name: Start Apache and Enable it on the every boot
       service: name=apache2 state=started enabled=yes
...
